version: '3.8'

services:
  postgres-database:
    image: postgres
    container_name: ''
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'projectRocketSeat'
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD: 
    networks:
      - backend

networks:
  backend:
